// Generated by tool/test_execution/generate_suites.py.
import 'package:flutter_test/flutter_test.dart';

import '../helpers/suite.dart';
import 'modules.dart';

void main() {
  verifySuiteManifest();
  group('app_shell_test.dart', caseEntrypoints['app_shell_cases.dart']!);
  group(
    'auth/connect_page_test.dart',
    caseEntrypoints['auth/connect_page_cases.dart']!,
  );
  group(
    'home/home_page_test.dart',
    caseEntrypoints['home/home_page_cases.dart']!,
  );
  group(
    'settings_page_test.dart',
    caseEntrypoints['settings_page_cases.dart']!,
  );
}
