// Generated by tool/test_execution/generate_suites.py.
import 'package:flutter_test/flutter_test.dart';

import '../helpers/suite.dart';
import 'modules.dart';

void main() {
  verifySuiteManifest();
  group(
    'catalog/catalog_browse_test.dart',
    caseEntrypoints['catalog/catalog_browse_cases.dart']!,
  );
  group(
    'catalog/item_detail_test.dart',
    caseEntrypoints['catalog/item_detail_cases.dart']!,
  );
  group(
    'catalog/library_filter_test.dart',
    caseEntrypoints['catalog/library_filter_cases.dart']!,
  );
  group(
    'catalog/shelf_grid_scroll_rebuild_test.dart',
    caseEntrypoints['catalog/shelf_grid_scroll_rebuild_cases.dart']!,
  );
}
