// Generated by tool/test_execution/generate_suites.py.
import '../app/window_geometry_cases.dart' as case0;
import '../app_shell_cases.dart' as case1;
import '../auth/auth_controller_cases.dart' as case2;
import '../auth/connect_page_cases.dart' as case3;
import '../auth/server_list_store_cases.dart' as case4;
import '../catalog/catalog_browse_cases.dart' as case5;
import '../catalog/catalog_cache_cases.dart' as case6;
import '../catalog/catalog_controller_cases.dart' as case7;
import '../catalog/emby_catalog_client_cases.dart' as case8;
import '../catalog/item_detail_cases.dart' as case9;
import '../catalog/library_filter_cases.dart' as case10;
import '../catalog/shelf_grid_scroll_rebuild_cases.dart' as case11;
import '../emby/emby_client_cases.dart' as case12;
import '../emby/emby_device_cases.dart' as case13;
import '../emby/emby_item_image_cases.dart' as case14;
import '../emby/emby_socket_cases.dart' as case15;
import '../emby/emby_url_cases.dart' as case16;
import '../emby/media_source_format_cases.dart' as case17;
import '../home/home_page_cases.dart' as case18;
import '../home/library_nav_prefs_cases.dart' as case19;
import '../library/item_format_cases.dart' as case20;
import '../player/danmaku/dandanplay_client_cases.dart' as case21;
import '../player/danmaku/danmaku_controller_cases.dart' as case22;
import '../player/danmaku/danmaku_hash_cases.dart' as case23;
import '../player/danmaku/danmaku_layout_cases.dart' as case24;
import '../player/danmaku/danmaku_renderer_cases.dart' as case25;
import '../player/danmaku/danmaku_settings_cases.dart' as case26;
import '../player/desktop_player_window_host_cases.dart' as case27;
import '../player/device_profile_cases.dart' as case28;
import '../player/emby_playback_client_cases.dart' as case29;
import '../player/mpv_video_backend_cases.dart' as case30;
import '../player/playback_check_in_cases.dart' as case31;
import '../player/playback_http_proxy_cases.dart' as case32;
import '../player/playback_resolver_cases.dart' as case33;
import '../player/playback_session_cases.dart' as case34;
import '../player/playback_session_snapshot_cases.dart' as case35;
import '../player/playback_wake_lock_cases.dart' as case36;
import '../player/player_controls_cases.dart' as case37;
import '../player/player_host_command_cases.dart' as case38;
import '../player/player_process_control_cases.dart' as case39;
import '../player/player_process_protocol_cases.dart' as case40;
import '../player/player_runtime_options_cases.dart' as case41;
import '../player/player_settings_cases.dart' as case42;
import '../player/player_window_cases.dart' as case43;
import '../player/player_window_launch_cases.dart' as case44;
import '../settings_page_cases.dart' as case45;
import '../widgets/app_empty_view_cases.dart' as case46;
import '../widgets/app_hover_card_cases.dart' as case47;
import '../widgets/backdrop_scrim_cases.dart' as case48;
import '../widgets/liquid_glass_cases.dart' as case49;
import '../widgets/media_image_cases.dart' as case50;
import '../widgets/poster_card_cases.dart' as case51;
import '../widgets/scrim_icon_button_cases.dart' as case52;
import '../widgets/skeleton_cases.dart' as case53;

// Import every module once; registering one group calls only its main().
// Importing widget modules alone does not install Flutter's HTTP mock.
const caseEntrypoints = <String, void Function()>{
  'app/window_geometry_cases.dart': case0.main,
  'app_shell_cases.dart': case1.main,
  'auth/auth_controller_cases.dart': case2.main,
  'auth/connect_page_cases.dart': case3.main,
  'auth/server_list_store_cases.dart': case4.main,
  'catalog/catalog_browse_cases.dart': case5.main,
  'catalog/catalog_cache_cases.dart': case6.main,
  'catalog/catalog_controller_cases.dart': case7.main,
  'catalog/emby_catalog_client_cases.dart': case8.main,
  'catalog/item_detail_cases.dart': case9.main,
  'catalog/library_filter_cases.dart': case10.main,
  'catalog/shelf_grid_scroll_rebuild_cases.dart': case11.main,
  'emby/emby_client_cases.dart': case12.main,
  'emby/emby_device_cases.dart': case13.main,
  'emby/emby_item_image_cases.dart': case14.main,
  'emby/emby_socket_cases.dart': case15.main,
  'emby/emby_url_cases.dart': case16.main,
  'emby/media_source_format_cases.dart': case17.main,
  'home/home_page_cases.dart': case18.main,
  'home/library_nav_prefs_cases.dart': case19.main,
  'library/item_format_cases.dart': case20.main,
  'player/danmaku/dandanplay_client_cases.dart': case21.main,
  'player/danmaku/danmaku_controller_cases.dart': case22.main,
  'player/danmaku/danmaku_hash_cases.dart': case23.main,
  'player/danmaku/danmaku_layout_cases.dart': case24.main,
  'player/danmaku/danmaku_renderer_cases.dart': case25.main,
  'player/danmaku/danmaku_settings_cases.dart': case26.main,
  'player/desktop_player_window_host_cases.dart': case27.main,
  'player/device_profile_cases.dart': case28.main,
  'player/emby_playback_client_cases.dart': case29.main,
  'player/mpv_video_backend_cases.dart': case30.main,
  'player/playback_check_in_cases.dart': case31.main,
  'player/playback_http_proxy_cases.dart': case32.main,
  'player/playback_resolver_cases.dart': case33.main,
  'player/playback_session_cases.dart': case34.main,
  'player/playback_session_snapshot_cases.dart': case35.main,
  'player/playback_wake_lock_cases.dart': case36.main,
  'player/player_controls_cases.dart': case37.main,
  'player/player_host_command_cases.dart': case38.main,
  'player/player_process_control_cases.dart': case39.main,
  'player/player_process_protocol_cases.dart': case40.main,
  'player/player_runtime_options_cases.dart': case41.main,
  'player/player_settings_cases.dart': case42.main,
  'player/player_window_cases.dart': case43.main,
  'player/player_window_launch_cases.dart': case44.main,
  'settings_page_cases.dart': case45.main,
  'widgets/app_empty_view_cases.dart': case46.main,
  'widgets/app_hover_card_cases.dart': case47.main,
  'widgets/backdrop_scrim_cases.dart': case48.main,
  'widgets/liquid_glass_cases.dart': case49.main,
  'widgets/media_image_cases.dart': case50.main,
  'widgets/poster_card_cases.dart': case51.main,
  'widgets/scrim_icon_button_cases.dart': case52.main,
  'widgets/skeleton_cases.dart': case53.main,
};
