// Generated by tool/test_execution/generate_suites.py.
import 'package:flutter_test/flutter_test.dart';

import '../helpers/suite.dart';
import 'modules.dart';

void main() {
  verifySuiteManifest();
  group(
    'player/desktop_player_window_host_test.dart',
    caseEntrypoints['player/desktop_player_window_host_cases.dart']!,
  );
  group(
    'player/player_controls_test.dart',
    caseEntrypoints['player/player_controls_cases.dart']!,
  );
  group(
    'player/player_window_test.dart',
    caseEntrypoints['player/player_window_cases.dart']!,
  );
}
