// Generated by tool/test_execution/generate_suites.py.
import 'package:flutter_test/flutter_test.dart';

import '../helpers/suite.dart';
import 'modules.dart';

void main() {
  verifySuiteManifest();
  group(
    'player/playback_http_proxy_test.dart',
    caseEntrypoints['player/playback_http_proxy_cases.dart']!,
  );
}
