// Generated by tool/test_execution/generate_suites.py.
import 'package:flutter_test/flutter_test.dart';

import '../helpers/suite.dart';
import 'modules.dart';

void main() {
  verifySuiteManifest();
  group(
    'catalog/catalog_controller_test.dart',
    caseEntrypoints['catalog/catalog_controller_cases.dart']!,
  );
  group(
    'player/danmaku/danmaku_renderer_test.dart',
    caseEntrypoints['player/danmaku/danmaku_renderer_cases.dart']!,
  );
  group(
    'widgets/app_empty_view_test.dart',
    caseEntrypoints['widgets/app_empty_view_cases.dart']!,
  );
  group(
    'widgets/app_hover_card_test.dart',
    caseEntrypoints['widgets/app_hover_card_cases.dart']!,
  );
  group(
    'widgets/backdrop_scrim_test.dart',
    caseEntrypoints['widgets/backdrop_scrim_cases.dart']!,
  );
  group(
    'widgets/liquid_glass_test.dart',
    caseEntrypoints['widgets/liquid_glass_cases.dart']!,
  );
  group(
    'widgets/media_image_test.dart',
    caseEntrypoints['widgets/media_image_cases.dart']!,
  );
  group(
    'widgets/poster_card_test.dart',
    caseEntrypoints['widgets/poster_card_cases.dart']!,
  );
  group(
    'widgets/scrim_icon_button_test.dart',
    caseEntrypoints['widgets/scrim_icon_button_cases.dart']!,
  );
  group(
    'widgets/skeleton_test.dart',
    caseEntrypoints['widgets/skeleton_cases.dart']!,
  );
}
