name: rillight
description: "灯川 Rillight desktop Emby client"
publish_to: 'none'
version: 0.1.7+8

environment:
  sdk: ^3.11.5

dependencies:
  dio: ^5.11.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ffi: ^2.1.4
  win32: ^5.14.0
  go_router: ^16.2.0
  intl: any
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^2.0.1
  path_provider: ^2.1.6
  screen_retriever: ^0.2.0
  window_manager: ^0.5.2
  desktop_multi_window: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_async: ^1.3.3

flutter:
  generate: true
  uses-material-design: true
