# The manifest is the single authority for archive URLs and SHA256.
file(READ "${CMAKE_CURRENT_LIST_DIR}/dependencies.json" MANIFEST)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_LIST_DIR}/dependencies.json")
function(rillight_archive NAME OUT)
  string(JSON URL GET "${MANIFEST}" windows ${NAME} url)
  string(JSON HASH GET "${MANIFEST}" windows ${NAME} sha256)
  string(JSON FILE GET "${MANIFEST}" windows ${NAME} archive)
  if(NOT RILLIGHT_ARCHIVE_CACHE)
    set(RILLIGHT_ARCHIVE_CACHE "${CMAKE_BINARY_DIR}")
  endif()
  set(ARCHIVE "${RILLIGHT_ARCHIVE_CACHE}/${FILE}")
  set(DEST "${CMAKE_BINARY_DIR}/rillight_native/${NAME}-${HASH}")
  if(EXISTS "${ARCHIVE}")
    file(SHA256 "${ARCHIVE}" ACTUAL)
    if(NOT ACTUAL STREQUAL HASH)
      message(FATAL_ERROR "Rillight archive SHA256 mismatch: ${ARCHIVE}")
    endif()
  else()
    file(DOWNLOAD "${URL}" "${ARCHIVE}" EXPECTED_HASH "SHA256=${HASH}" TLS_VERIFY ON STATUS STATUS)
    list(GET STATUS 0 RESULT)
    if(NOT RESULT EQUAL 0)
      message(FATAL_ERROR "Rillight native download failed: ${STATUS}")
    endif()
  endif()
  if(NOT EXISTS "${DEST}/.verified")
    file(MAKE_DIRECTORY "${DEST}")
    file(ARCHIVE_EXTRACT INPUT "${ARCHIVE}" DESTINATION "${DEST}")
    file(WRITE "${DEST}/.verified" "${HASH}\n")
  endif()
  set(${OUT} "${DEST}" PARENT_SCOPE)
endfunction()
rillight_archive(mpv RILLIGHT_MPV)
rillight_archive(angle RILLIGHT_ANGLE)
