"""Keep normal flutter test discovery small without hiding new test files."""

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TEST = ROOT / "test"
HEADER = "// Generated by tool/test_execution/generate_suites.py.\n"

# The unit group is the wall-clock long pole (~15s single-isolate on the
# reference machine). playback_http_proxy alone measured ~8s of that, so it
# runs in its own suite and both unit isolates stay near ~7s. Re-measure and
# rebalance when unit modules change materially.
UNIT_LONG_POLE = frozenset({"player/playback_http_proxy_cases.dart"})



def group_for(path, source):
    if "testWidgets(" not in source:
        # Registering testWidgets installs Flutter's HTTP mock for the entire
        # process. Keep real socket/HTTP tests in a separate test process.
        return "unit"
    if "integration" not in source:
        return "widgets"
    feature = path.split("/", 1)[0]
    return feature if feature in ("catalog", "player") else "app"


def generated_files():
    modules = sorted(p.relative_to(TEST).as_posix() for p in TEST.rglob("*_cases.dart"))
    groups = {name: [] for name in ("app", "catalog", "player", "unit", "widgets")}
    for module in modules:
        groups[group_for(module, (TEST / module).read_text(encoding="utf-8"))].append(module)
    result = {}
    groups["unit_b"] = [m for m in groups["unit"] if m in UNIT_LONG_POLE]
    groups["unit"] = [m for m in groups["unit"] if m not in UNIT_LONG_POLE]
    shared = [HEADER.rstrip()]
    shared += [f"import '../{path}' as case{i};" for i, path in enumerate(modules)]
    shared += ["", "// Import every module once; registering one group calls only its main().",
               "// Importing widget modules alone does not install Flutter's HTTP mock.",
               "const caseEntrypoints = <String, void Function()>{"]
    shared += [f"  '{path}': case{i}.main," for i, path in enumerate(modules)]
    shared += ["};", ""]
    result[TEST / "suites" / "modules.dart"] = "\n".join(shared)
    for name, paths in groups.items():
        lines = [HEADER.rstrip(), "import 'package:flutter_test/flutter_test.dart';", ""]
        lines += ["import '../helpers/suite.dart';", "import 'modules.dart';", "", "void main() {", "  verifySuiteManifest();"]
        for path in paths:
            label = path.removesuffix("_cases.dart") + "_test.dart"
            single = f"  group('{label}', caseEntrypoints['{path}']!);"
            if len(single) <= 80:
                lines.append(single)
            else:
                lines += ["  group(", f"    '{label}',", f"    caseEntrypoints['{path}']!,", "  );"]
        lines += ["}", ""]
        result[TEST / "suites" / f"{name}_test.dart"] = "\n".join(lines)
    manifest = HEADER + "const caseModules = <String>[\n"
    manifest += "".join(f"  '{path}',\n" for path in modules)
    result[TEST / "helpers" / "suite_manifest.dart"] = manifest + "];\n"
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    expected = generated_files()
    for path in (TEST / "suites").glob("*_test.dart"):
        if path not in expected and path.read_text(encoding="utf-8").startswith(HEADER):
            if args.check:
                stale.append(path.relative_to(ROOT).as_posix())
            else:
                assert path.resolve().parent == (TEST / "suites").resolve()
                path.unlink()
    for path, source in expected.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != source:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(source, encoding="utf-8", newline="\n")
    if stale:
        parser.exit(1, "Run python tool/test_execution/generate_suites.py: " + ", ".join(stale) + "\n")


if __name__ == "__main__":
    main()
